spring:
  redis:
    database: 0 # Redis数据库索引（默认为0）,如果设置为1，那么存入的key-value都存放在select 1中
    host: 52.82.99.12 # Redis服务器地址
    port: 26378  # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

logging:
  config: classpath:logback-spring.xml  # springBoot2.0默认就会找这个文件的

swagger_enable: true

